server:
    port: 8082
    
logging:
    level:
      org:
        springframework:
          security: DEBUG
            
spring:
  security:
    Oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bassure
          jwk-set-uri: http://localhost:8080/realms/bassure/protocol/openid-connect/certs
          
jwt:
  auth:
    converter:
      resource-id: ems
#      principal-attribute: preferred_username
      
